version: "3.7"

services:
    ionic:
        build: .
        container_name: dynpages-ionic
        entrypoint: .docker/entrypoint.sh
        restart: unless-stopped
        ports:
            - 4200:4200
        volumes:
            - .:/home/node/dynpages-client
            - ~/.wakatime.cfg:/home/node/.wakatime.cfg
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - ingress

networks:
    ingress:
        driver: bridge
